
eureka:
  instance:
    instance-id: 'power-1'
    lease-renewal-interval-in-seconds: 1      # 发送心跳的时间
    lease-expiration-duration-in-seconds: 3   # 多久不发送心跳就移除
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka
#    enabled: false
#    fetch-registry: false
spring:
  application:
    name: 'POWER'
server:
  port: 6001